# Generated by Django 5.1.3 on 2025-02-13 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_new_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="new_field",
        ),
    ]
