# Generated by Django 5.1.3 on 2024-12-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_restaurant_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="photo",
            field=models.ImageField(blank=True, upload_to="restaurants/"),
        ),
    ]
