# Generated by Django 5.1.3 on 2024-11-30 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(default="General", max_length=50),
        ),
    ]
