# Generated by Django 5.1.3 on 2024-12-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_order_eta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Paid", "Paid"),
                    ("Pending", "Pending"),
                    ("Preparing", "Preparing"),
                    ("En Route", "En Route"),
                    ("Delivered", "Delivered"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
